kube-prometheus-stack:
  crds:
    enabled: false
  defaultRules:
    create: true
  global:
    rbac:
      create: true
      createAggregateClusterRoles: true
  alertmanager:
    enabled: true
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 32Mi
    ingress:
      enabled: false
    alertmanagerSpec:
      replicas: 1
    externalUrl: https://alertmanager.alexlebens.dev
  grafana:
    enabled: false
  kubeApiServer:
    tlsConfig:
      insecureSkipVerify: true
  kube-state-metrics:
    selfMonitor:
      enabled: true
  prometheusOperator:
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 32Mi
    admissionWebhooks:
      enabled: true
    namespaces:
      releaseNamespace: true
      additional:
        - kube-system
        - argocd
        - astro
        - authentik
        - cert-manager
        - element-web
        - external-secrets
        - ghost
        - loki
        - matrix-synapse
        - traefik
        - vault
  prometheus:
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 32Mi
    ingress:
      enabled: false
    prometheusSpec:
      scrapeInterval: 30s
      retention: 7d
      externalUrl: https://prometheus.alexlebens.dev
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: do-block-storage
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
