external-secrets:
  resources:
    limits:
      memory: 128Mi
      cpu: 50m
    requests:
      cpu: 10m
      memory: 32Mi
  serviceMonitor:
    enabled: true
  webhook:
    resources:
      limits:
        memory: 128Mi
        cpu: 50m
      requests:
        cpu: 10m
        memory: 32Mi
  certController:
    resources:
      limits:
        memory: 128Mi
        cpu: 50m
      requests:
        cpu: 10m
        memory: 32Mi
