apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ghost-password-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: ghost-password-secret
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: {{ .Release.Name }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  data:
    - secretKey: ghost-password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /ghost/auth
        metadataPolicy: None
        property: ghost-password
    - secretKey: mysql-root-password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /ghost/auth
        metadataPolicy: None
        property: mysql-root-password
    - secretKey: mysql-replication-password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /ghost/auth
        metadataPolicy: None
        property: mysql-replication-password
    - secretKey: mysql-password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /ghost/auth
        metadataPolicy: None
        property: mysql-password
