destination: cl02do
git:
  repo: git@github.com:alexlebens/alexlebens-dev.git
  revision: HEAD
  path: clusters/cl02do
applicationSet:
  - name: applications
    syncPolicy:
      automated:
        enabled: true
        prune: true
        selfheal: false
      syncOptions:
        - CreateNamespace=true
        - ApplyOutOfSyncOnly=true
        - ServerSideApply=false
        - PruneLast=true
  - name: deployment
    namespace: argocd
    syncPolicy:
      automated:
        enabled: true
        prune: true
        selfheal: false
      syncOptions:
        - CreateNamespace=true
        - ApplyOutOfSyncOnly=true
        - ServerSideApply=false
        - PruneLast=true
  - name: platform
    syncPolicy:
      automated:
        enabled: true
        prune: true
        selfheal: false
      syncOptions:
        - CreateNamespace=true
        - ApplyOutOfSyncOnly=true
        - ServerSideApply=true
        - PruneLast=true
  - name: services
    syncPolicy:
      automated:
        enabled: true
        prune: true
        selfheal: false
      syncOptions:
        - CreateNamespace=true
        - ApplyOutOfSyncOnly=true
        - ServerSideApply=true
        - PruneLast=true
application:
  prometheusOperatorCrds:
    namespace: kube-system
    source:
      repo: git@github.com:alexlebens/alexlebens-dev.git
      revision: HEAD
      path: standalone/prometheus-operator-crds
      helm:
        releaseName: prometheus-operator-crds
    syncPolicy:
      automated:
        prune: true
      retry:
        limit: 10
        backoff:
          duration: 1m
          factor: 2
          maxDuration: 16m
      syncOptions:
        - CreateNamespace=false
        - ApplyOutOfSyncOnly=false
        - ServerSideApply=true
        - PruneLast=true
  metricsServer:
    namespace: kube-system
    source:
      repo: git@github.com:alexlebens/alexlebens-dev.git
      revision: HEAD
      path: standalone/metrics-server
      helm:
        releaseName: metrics-server
    syncPolicy:
      automated:
        prune: true
      retry:
        limit: 10
        backoff:
          duration: 1m
          factor: 2
          maxDuration: 16m
      syncOptions:
        - CreateNamespace=false
        - ApplyOutOfSyncOnly=false
        - ServerSideApply=true
        - PruneLast=true
