apiVersion: v2
name: matrix-synapse
version: 1.0.0
sources:
  - https://github.com/element-hq/synapse
  - https://github.com/matrix-org/matrix-hookshot
  - https://github.com/mautrix/discord
  - https://github.com/mautrix/whatsapp
  - https://gitlab.com/ananace/charts/-/tree/master/charts/matrix-synapse
dependencies:
  - name: matrix-synapse
    version: 3.9.2
    repository: https://ananace.gitlab.io/charts
  - name: matrix-hookshot
    version: 0.1.1
    repository: http://alexlebens.github.io/helm-charts
  - name: mautrix-discord
    version: 0.0.2
    repository: http://alexlebens.github.io/helm-charts
  - name: mautrix-whatsapp
    version: 0.0.3
    repository: http://alexlebens.github.io/helm-charts
  - name: redis
    version: 19.1.2
    repository: https://charts.bitnami.com/bitnami
appVersion: v1.104.0
