matrix-synapse:
  serverName: alexlebens.dev
  publicServerName: matrix.alexlebens.dev
  argoCD: true
  signingkey:
    job:
      enabled: false
  config:
    reportStats: false
    enableRegistration: true
    trustedKeyServers: []
  extraConfig:
    enable_metrics: true
    enable_registration_without_verification: false
    password_config:
      enabled: false
    sso:
      client_whitelist:
        - https://chat.alexlebens.dev/
      update_profile_information: true
  synapse:
    strategy:
      type: Recreate
    extraVolumes:
      - name: matrix-synapse-config-secret
        secret:
          secretName: matrix-synapse-config-secret
      - name: matrix-hookshot-config-secret
        secret:
          secretName: matrix-hookshot-config-secret
      - name: mautrix-discord-config-secret
        secret:
          secretName: mautrix-discord-config-secret
      - name: mautrix-whatsapp-config-secret
        secret:
          secretName: mautrix-whatsapp-config-secret
    extraVolumeMounts:
      - name: matrix-synapse-config-secret
        mountPath: /synapse/config/conf.d/oidc.yaml
        subPath: oidc.yaml
        readOnly: true
      - name: matrix-synapse-config-secret
        mountPath: /synapse/config/conf.d/config.yaml
        subPath: config.yaml
        readOnly: true
      - name: matrix-hookshot-config-secret
        mountPath: /synapse/config/conf.d/hookshot-registration.yaml
        subPath: hookshot-registration.yaml
        readOnly: true
      - name: mautrix-discord-config-secret
        mountPath: /synapse/config/conf.d/mautrix-discord-registration.yaml
        subPath: mautrix-discord-registration.yaml
        readOnly: true
      - name: mautrix-whatsapp-config-secret
        mountPath: /synapse/config/conf.d/mautrix-whatsapp-registration.yaml
        subPath: mautrix-whatsapp-registration.yaml
        readOnly: true
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 50m
        memory: 100Mi
  workers:
    default:
      replicaCount: 0
    generic_worker:
      enabled: false
    pusher:
      enabled: false
    appservice:
      enabled: false
    federation_sender:
      enabled: false
    media_repository:
      enabled: false
    user_dir:
      enabled: false
  wellknown:
    enabled: true
    server:
      m.server: matrix.alexlebens.dev:443
    client:
      m.homeserver:
        base_url: https://matrix.alexlebens.dev
  postgresql:
    enabled: false
  externalPostgresql:
    host: private-db-postgresql-nyc1-cl02do-do-user-13463908-0.c.db.ondigitalocean.com
    port: 25061
    username: synapse
    database: synapse-pool
    existingSecret: matrix-synapse-config-secret
    existingSecretPasswordKey: postgresql-password
  redis:
    enabled: false
  externalRedis:
    host: matrix-synapse-redis-headless
    port: 6379
    existingSecret: matrix-synapse-config-secret
    existingSecretPasswordKey: redis-password
  persistence:
    enabled: true
    storageClass: do-block-storage
    accessMode: ReadWriteOnce
    size: 10Gi
  volumePermissions:
    enabled: true
    uid: 666
    gid: 666
    resources:
      requests:
        memory: 128Mi
        cpu: 10m
  ingress:
    enabled: true
    className: traefik
    traefikPaths: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      cert-manager.io/cluster-issuer: letsencrypt-issuer
    includeUnderscoreSynapse: true
    includeServerName: true
    tls:
      - secretName: matrix-synapse-secret-tls
        hosts:
          - matrix.alexlebens.dev
matrix-hookshot:
  ingress:
    webhook:
      enabled: true
      className: traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
        cert-manager.io/cluster-issuer: letsencrypt-issuer
      host: matrix-hookshot.alexlebens.dev
    appservice:
      enabled: false
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  hookshot:
    existingSecret: matrix-hookshot-config-secret
    existingRegistrationSecret: matrix-hookshot-config-secret
    existingPasskeySecret: matrix-hookshot-config-secret
redis:
  architecture: standalone
  auth:
    enabled: true
    existingSecret: matrix-synapse-config-secret
    existingSecretPasswordKey: redis-password
  persistence:
    enabled: false
mautrix-discord:
  ingress:
    enabled: true
    className: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      cert-manager.io/cluster-issuer: letsencrypt-issuer
    host: matrix-discord.alexlebens.dev
  persistence:
    enabled: ture
    size: 500Mi
  mautrixDiscord:
    existingSecret: mautrix-discord-config-secret
    existingRegistrationSecret: mautrix-discord-config-secret
mautrix-whatsapp:
  ingress:
    enabled: true
    className: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      cert-manager.io/cluster-issuer: letsencrypt-issuer
    host: matrix-whatsapp.alexlebens.dev
  persistence:
    enabled: ture
    size: 500Mi
  mautrixWhatsapp:
    existingSecret: mautrix-whatsapp-config-secret
    existingRegistrationSecret: mautrix-whatsapp-config-secret
