apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: matrix-synapse-config-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: {{ .Release.Name }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  data:
    - secretKey: redis-password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /matrix-synapse/config
        metadataPolicy: None
        property: redis-password
    - secretKey: postgresql-password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /matrix-synapse/config
        metadataPolicy: None
        property: postgresql-password
    - secretKey: oidc.yaml
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /matrix-synapse/config
        metadataPolicy: None
        property: oidc.yaml
    - secretKey: config.yaml
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /matrix-synapse/config
        metadataPolicy: None
        property: config.yaml

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: matrix-hookshot-config-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: {{ .Release.Name }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  data:
    - secretKey: config.yml
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /matrix-synapse/hookshot
        metadataPolicy: None
        property: config
    - secretKey: registration.yml
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /matrix-synapse/hookshot
        metadataPolicy: None
        property: registration
    - secretKey: hookshot-registration.yaml
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /matrix-synapse/hookshot
        metadataPolicy: None
        property: registration
    - secretKey: passkey.pem
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /matrix-synapse/hookshot
        metadataPolicy: None
        property: passkey
