traefik:
  deployment:
    kind: DaemonSet
  ingressClass:
    enabled: true
    isDefaultClass: true
  ingressRoute:
    dashboard:
      enabled: false
  providers:
    kubernetesCRD:
      allowCrossNamespace: true
    kubernetesIngress:
      publishedService:
        enabled: true
  metrics:
    service:
      enabled: true
  ports:
    traefik:
      expose:
        default: false
        internal: true
    web:
      port: 8000
      expose:
        default: true
        internal: true
      exposedPort: 80
      redirectTo:
        port: websecure
        priority: 10
      forwardedHeaders:
        insecure: false
      proxyProtocol:
        insecure: false
    websecure:
      port: 8443
      expose:
        default: true
        internal: true
      exposedPort: 443
      http3:
        enabled: false
      forwardedHeaders:
        insecure: false
      proxyProtocol:
        insecure: false
      tls:
        enabled: true
    metrics:
      expose:
        default: false
        internal: true
  tlsStore:
    default:
      defaultCertificate:
        secretName: traefik-secret-tls
  service:
    enabled: true
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/do-loadbalancer-size-unit: "1"
  resources:
    limits:
      cpu: 100m
      memory: 256Mi  
    requests:
      cpu: 10m
      memory: 128Mi
