vault:
  global:
    enabled: true
    tlsDisable: true
    serverTelemetry:
      prometheusOperator: true
  injector:
    enabled: false
  server:
    enabled: true
    image:
      repository: hashicorp/vault
      tag: "1.16.2"
    resources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        memory: 128Mi
        cpu: 10m
    ingress:
      enabled: false
    route:
      enabled: false
    authDelegator:
      enabled: false
    networkPolicy:
      enabled: false
    service:
      enabled: true
      active:
        enabled: true
      standby:
        enabled: true
      instanceSelector:
        enabled: true
    dataStorage:
      enabled: true
      size: 5Gi
      mountPath: /vault/data
      accessMode: ReadWriteOnce
    auditStorage:
      enabled: false
    dev:
      enabled: false
    standalone:
      enabled: true
    ha:
      enabled: false
    serviceAccount:
      create: true
      serviceDiscovery:
        enabled: true
  ui:
    enabled: true
    publishNotReadyAddresses: true
    activeVaultPodOnly: false
    serviceType: "ClusterIP"
    serviceNodePort: null
    externalPort: 8200
    targetPort: 8200
  csi:
    enabled: false
  serverTelemetry:
    serviceMonitor:
      enabled: true
    prometheusRules:
      enabled: true
      rules:
        - alert: vault-HighResponseTime
          annotations:
            message: The response time of Vault is over 500ms on average over the last 5 minutes.
          expr: vault_core_handle_request{quantile="0.5", namespace="mynamespace"} > 500
          for: 5m
          labels:
            severity: warning
        - alert: vault-HighResponseTime
          annotations:
            message: The response time of Vault is over 1s on average over the last 5 minutes.
          expr: vault_core_handle_request{quantile="0.5", namespace="mynamespace"} > 1000
          for: 5m
          labels:
            severity: critical
