apiVersion: v2
name: authentik
version: 1.0.0
sources:
  - https://github.com/goauthentik/authentik
  - https://github.com/goauthentik/helm
  - https://github.com/alexlebens/helm-charts/charts/postgres-cluster
dependencies:
  - name: authentik
    version: 2024.4.2
    repository: https://charts.goauthentik.io/
appVersion: "2024.2.2"
