apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: outline-key-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: {{ .Release.Name }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  data:
    - secretKey: secret-key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /outline/key
        metadataPolicy: None
        property: secret-key
    - secretKey: utils-key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /outline/key
        metadataPolicy: None
        property: utils-key

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: outline-oidc-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: {{ .Release.Name }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  data:
    - secretKey: client
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /authentik/oidc/outline
        metadataPolicy: None
        property: client
    - secretKey: secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /authentik/oidc/outline
        metadataPolicy: None
        property: secret

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: outline-database-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: {{ .Release.Name }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  data:
    - secretKey: username
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /digital-ocean/alexlebens-dev/outline
        metadataPolicy: None
        property: username
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /digital-ocean/alexlebens-dev/outline
        metadataPolicy: None
        property: password
    - secretKey: dbname
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /digital-ocean/alexlebens-dev/outline
        metadataPolicy: None
        property: dbname
    - secretKey: host
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /digital-ocean/alexlebens-dev/outline
        metadataPolicy: None
        property: host
    - secretKey: port
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /digital-ocean/alexlebens-dev/outline
        metadataPolicy: None
        property: port

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: outline-bucket-auth
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: {{ .Release.Name }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /digital-ocean/alexlebens-dev/auth
        metadataPolicy: None
        property: ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /digital-ocean/alexlebens-dev/auth
        metadataPolicy: None
        property: ACCESS_SECRET_KEY
