apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tailscale-cl02do-alertmanager
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: tailscale-cl02do-alertmanager
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: tailscale
    app.kubernetes.io/part-of: {{ .Release.Name }}
spec:
  ingressClassName: tailscale
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kube-prometheus-stack-alertmanager
                port:
                  number: 9093

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tailscale-cl02do-prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: tailscale-cl02do-prometheus
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: tailscale
    app.kubernetes.io/part-of: {{ .Release.Name }}
spec:
  ingressClassName: tailscale
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kube-prometheus-stack-prometheus
                port:
                  number: 9090
