{{- range $index, $stack := .Values.applicationSet }}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: "{{ $stack.name }}-{{ $.Values.destination }}"
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: "{{ $stack.name }}-{{ $.Values.destination }}"
    app.kubernetes.io/instance: "{{ $stack.name }}-{{ $.Values.destination }}"
    app.kubernetes.io/version: {{ $.Chart.AppVersion }}
    app.kubernetes.io/component: argocd
    app.kubernetes.io/part-of: {{ $.Release.Name }}
spec:
  syncPolicy:
    applicationsSync: create-only
    preserveResourcesOnDeletion: true
  generators:
    - git:
        repoURL: {{ $.Values.git.repo }}
        revision: {{ $.Values.git.revision }}
        directories:
          - path: "clusters/{{ $.Values.destination }}/{{ $stack.name }}/*"
  template:
    metadata:
      name: "{{ `{{path.basename}}` }}-{{ $.Values.destination }}"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      destination:
        name: {{ ternary "in-cluster" $.Values.destination (eq $.Values.destination "cl01tl")}}
        namespace: "{{ $stack.namespace | default `{{path.basename}}` }}"
      project: default
      revisionHistoryLimit: 3
      source:
        repoURL: {{ $.Values.git.repo }}
        targetRevision: {{ $.Values.git.revision }}
        path: "{{ `{{path}}` }}"
        helm:
          releaseName: "{{ `{{path.basename}}` }}"
      syncPolicy:
        {{- if $stack.syncPolicy.automated.enabled }}
        automated:
          prune: {{ $stack.syncPolicy.automated.prune | default false }}
          selfHeal: {{ $stack.syncPolicy.automated.selfHeal | default false }}
        {{- end }}
        retry:
          limit: 3
          backoff:
            duration: 1m
            factor: 2
            maxDuration: 15m
        syncOptions:
          {{- toYaml $stack.syncPolicy.syncOptions | nindent 10 }}
{{- end }}
