destination: cl01tl
git:
  repo: git@github.com:alexlebens/alexlebens-dev.git
  revision: HEAD
applicationSet:
  - name: deployment
    namespace: argocd
    syncPolicy:
      automated:
        enabled: true
        prune: true
        selfheal: true
      syncOptions:
        - CreateNamespace=true
        - ApplyOutOfSyncOnly=true
        - ServerSideApply=true
        - PruneLast=true
  - name: applications
    syncPolicy:
      automated:
        enabled: true
        prune: true
        selfheal: false
      syncOptions:
        - CreateNamespace=true
        - ApplyOutOfSyncOnly=true
        - ServerSideApply=false
        - PruneLast=true
