apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-key-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: {{ .Release.Name }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  data:
    - secretKey: key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /authentik/key
        metadataPolicy: None
        property: key

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql-cl02do-authentik-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: {{ .Release.Name }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  data:
    - secretKey: host
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /digital-ocean/alexlebens-dev/authentik
        metadataPolicy: None
        property: host
    - secretKey: database
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /digital-ocean/alexlebens-dev/authentik
        metadataPolicy: None
        property: database
    - secretKey: user
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /digital-ocean/alexlebens-dev/authentik
        metadataPolicy: None
        property: user
    - secretKey: password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /digital-ocean/alexlebens-dev/authentik
        metadataPolicy: None
        property: password
    - secretKey: port
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /digital-ocean/alexlebens-dev/authentik
        metadataPolicy: None
        property: port
    - secretKey: pgbouncer
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /digital-ocean/alexlebens-dev/authentik
        metadataPolicy: None
        property: pgbouncer
    - secretKey: sslmode
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /digital-ocean/alexlebens-dev/authentik
        metadataPolicy: None
        property: sslmode
    - secretKey: sslrootcert
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /digital-ocean/alexlebens-dev/authentik
        metadataPolicy: None
        property: sslrootcert
