argo-cd:
  crds:
    install: true
  configs:
    cm:
      admin.enabled: true
      url: https://argocd.alexlebens.dev
      statusbadge.enabled: "true"
    params:
      server.insecure: true
  server:
    replicas: 1
    ingress:
      enabled: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  dex:
    enabled: true
  redis-ha:
    enabled: false
  controller:
    replicas: 1
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  repoServer:
    replicas: 1
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  applicationSet:
    replicas: 1
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
